### PR TITLE
Starting work on uses constraints

### PR DESCRIPTION
**Pull request by maier49**
Currently throws an NPE when saving Packages
with USES constraints.

### CODE REVIEW

**Comment by maier49** [comment]
I'm pretty confident that the actual parsing and creating of uses constraints is working, but whenever a Package involved in a 'USES' relationship is saved an NPE gets thrown.

**Comment by maier49** [comment]
I resolved the NPE issues I was seeing by removing all the uses constraints from the packages, saving them all, and then replacing them and saving again.

It seems like this issue: https://jira.spring.io/browse/DATAGRAPH-216, might not be resolved after all. I left a comment and saw that someone else had made a similar comment very recently. That would explain this issue with uses constraints as well as the fact that you had to save packages before bundles in order to get it to work.

**Comment by jgriff** [comment]
@maier49, I'm going to hold off on this PR.  I've been thinking about how we should model a "uses" constraint, and it's not exactly right to simply relate `(package1)-[:USES]->(package2)` because the "uses" is really a function of the exporting bundle (ie, it's possible to have another/different provider of that package export it without the `uses` constraint tied to it).  So we have to relate back to which bundle the constraint is coming from.

What I'm thinking is another entity labeled `UsesConstraint`, such that:

```
(bundle1)-[:EXPORTS]->(package1)-[:CONSTRAINED_BY]->(usesConstraint)
```

Then the `usesConstraint` entity would have 3 outgoing relationships:

```
(usesConstraint)-[:PROVIDER]->(bundle1).
(usesConstraint)-[:PACKAGE]->(package1),
(usesConstraint)-[:USES]->(package2)
```

**Comment by maier49** [comment]
@jgriff , Ignoring the constraints of neo4j I would think that this would really be a relationship between EXPORTS and Package. Since that's not possible I just  threw together something that worked as a first go, but your idea makes more sense.Whenever you finish that(or if you want me to add it to this branch), I'll integrate it with my other changes here.

**Comment by jgriff** [comment]
Your solution is a great starting point (and is also what I thought at first).  But then it occurred to me that we'd lose the context for "which bundle has this constraint?".

I'll work it on a branch and throw it up for you to pull from.  Then, if we get somewhere that looks promising we'll merge it to `master`.  Sound good?

**Comment by maier49** [comment]
:thumbsup:

**Comment by jgriff** [comment]
OK, I think I've got something pretty exciting here.  Try out branch `feature/uses-constraints`.

Note that you _do not need to do any manual hooking of the relationships for a `UsesConstraint` instance_.  That will be done implicitly for you as you add a `UsesConstraint` to the model (ie, to a `Package` and then to a `PackageExport`).  You simply specify the package being used, and add it to the `PackageExport`.

``` java
UsesConstraint uc = new UsesConstraint("this.package.is.used");
package.addUsesConstraint(uc);
```

Here's a query to get you started.  Note you can also double-click a node in the neo4j browser to retrieve all of its adjacent nodes.

```
MATCH (b)-[:EXPORTS]->(p)<-[:PACKAGE]-(uc:UsesConstraint)-[:USES]->(used)
RETURN b,p,uc,used LIMIT 10;
```

**Comment by jgriff** [comment]
Here's a screenshot of a sample I ran, where I injected a fake uses constraint on `com.foo` of every package export.
screen shot 2014-07-06 at 9 08 34 pm

**Comment by jgriff** [comment]
Closing this PR in preference for a new one that targets `feature/uses-constraints`.

**Pull request closed without merging**
